inference:
  source: 0        # rtsp url или индекс камеры
  model_name: "yolov8s_rknn"

  drone_height: 40.0
  fov_degrees: 90.0

  clustering:
    eps: 0.00009
    min_samples: 2
    metric: "euclidean"
