training:
  project: "runs/drone_yolov8"
  epochs: 100
  imgsz: 640
  device: ${experiment.device}

  optimizer: "SGD"
  lr0: 0.01
  lrf: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1

  multi_scale: false
  degrees: 0.0
  translate: 0.1
  scale: 0.5
  shear: 0.0
  perspective: 0.0
  mixup: 0.0
  cos_lr: false
  close_mosaic: 0

  box: 7.5
  cls: 0.5
  dfl: 1.5
  dropout: 0.0
